language: ruby
rvm:
  - jruby-head
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - rbx-2
  - ruby-head
jdk:
  - openjdk7
  - oraclejdk7

sudo: false
cache: bundler

matrix:
  exclude:
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.1.6
      jdk: openjdk7
    - rvm: 2.1.6
      jdk: oraclejdk7
    - rvm: 2.2.2
      jdk: openjdk7
    - rvm: 2.2.2
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: rbx-2
      jdk: openjdk7
    - rvm: rbx-2
      jdk: oraclejdk7

env:
  - RAKE_TASK="test"

script: "bundle exec rake $RAKE_TASK"
